export enum ControllerResponseCode {
  SUCCESS = 'SUCCESS',
  ERROR_INVALID_PARAMETERS = 'ERROR_INVALID_PARAMETERS',
  ERROR_INVALID_ROUTE = 'ERROR_INVALID_ROUTE',
  ERROR_INTERNAL = 'ERROR_INTERNAL',
}
